language: php

php:
- 5.3
- 5.4
- 5.5
- 5.6
- hhvm

before_script:
- curl -s http://getcomposer.org/installer | php
- php composer.phar install -no-interaction --prefer-source --dev

script: 
- ./vendor/bin/phpunit --coverage-clover coverage.clover
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover